export const Types = {
  USERS_LOADING: 'USERS_LOADING',
  USERS_DATA: 'USERS_DATA',
  USER_LOADING: 'USER_LOADING',
  USER_DATA: 'USER_DATA',
  MODAL_VISIBLE: 'MODAL_VISIBLE',
  USERS_DATA_CLONE: 'USERS_DATA_CLONE',
};
